### ISSUE TITLE
PostgreSQL version in contributing.md no longer available.

### ISSUE THREAD

**Issue by ilearner777** [arrocke/gloss-translation#149]
**Describe the bug**
Installation instructions specify v14.7, however download site only offers v14.9 or 15.4. I installed 14.9. Let me know if this is the correct choice.

**To Reproduce**

1. Go to 'https://www.enterprisedb.com/downloads/postgres-postgresql-downloads'
2. Observe that v14.7 is not available

**Expected behavior**
Expected to find v14.7

**Screenshots**

**Environment (please complete the following information):**
Dev Environment

**Additional context**
At some point we may want to update contributing.md document.

**Comment by arrocke** [comment]
14.9 should be fine. Postgresql follows semver in their [versioning policy](https://www.postgresql.org/support/versioning/), which means that minor versions are backwards compatible. We should modify the docs to specify just version 14 rather than a specific minor version. That's consistent with node and npm where we don't specify a minor and patch version. @ilearner777 Do you want to handle this, when you get a chance?
