### ISSUE TITLE
Update to DATABASE_URL gets tracked

### ISSUE THREAD

**Issue by ilearner777** [arrocke/gloss-translation#150]
**Describe the bug**
1. Noticed that db.md states to update DATABASE_URL in file 'packages/api/.env.local', however this file does not exist. It is called .env instead.
2. Noticed that .gitignore file has .env.local after the # Next.js heading.

**To Reproduce**
1. Created fork
3. Cloned to local environment
4. Installed PostgreSQL
5. Create local database
6. Updated DATABASE_URL in file: ./packages/api/.env
7. Git marks .env file as changed.

**Expected behavior**
1. Expected to find file env.local
2. Expected that when made update to DATABASE_URL that the file would be ignored by git.

**Screenshots**

**Environment (please complete the following information):**
- Device: Laptop
- OS: Windows 11

**Additional context**
Should .gitignore be updated to contain */packages/api/.env*  instead of *.env.local*?

**Comment by arrocke** [comment]
This is by design. `.env.local` is for sensitive env vars or ones that apply only in your local environment. Our build tool `nx` will load both `.env` and `.env.local` with vars in `.env.local` overriding vars in `.env`. The reason we tell you to set the database url in `.env.local` is because your connection string is going to be different than mine so we don't want to check that into version control. If you want to open a PR that clarifies in the docs that `.env.local` needs to be added when setting up a new local environment, feel free.

**Comment by ilearner777** [comment]
Thanks. Your explanation makes perfect sense. Will create a copy of *.env*, naming it *.env.local*.
