### ISSUE TITLE
Glosses not being accepted or reverting back

### ISSUE THREAD

**Issue by BethedenMinistries** [arrocke/gloss-translation#183]
**Describe the bug**
When I attempted to replace a gloss of אֲשֶׁ֤ר in Ps 148.4 the gloss kept reverting back to what it originally was whenever I would press Tab. The gloss that I was trying to type in manually was already in the list, so I attempted to select it from the list, and it reverted again. When I selected it from the list a second time it finally staid.  

The dropdown menu for a gloss should not activate unless told to do so, since it interrupts the flow of the typing. When something is manually typed to replace a gloss, it should replace the gloss immediately without the drop down menu suggesting something automatically. This caused a lot of problems for me. 90% of the glosses I typed in to replace bad glosses were deleted by this function. 

I was using Chrome and the interface was in English and the glosses I was working on were the English ones.

**Comment by arrocke** [comment]
I did some testing, and I think the issue here is that when what you type matches something in the list even partially, it puts the focus on that rather than the add new option. If it didn't do that then both enter and tab would save your typed gloss. Let me see if I can fix this.

**Comment by arrocke** [comment]
Been thinking about this some more, and I think we have a tradeoff we need to consider. There are two ways we could design this:
1. Make it work like a search bar. As you type, you get suggestions that you can pick from, but ultimately whatever ends up in the text input is what gets saved. This prioritizes speed of typing, since you can type what you want and move on. This also could result in more typos since the user may not pick from a list
2. Make it work like a combobox. As you type, the options are filtered. To select what you want the value to be, you have to pick an option from the list, which could include to create a new option. This may be slower for those who are comfortable typing, but it would potentially produce fewer typos since the user has to make an explicit action to produce a new gloss.

I know that you are used to the first option, but I want us to at least consider these tradeoffs. I ultimately don't have a strong preference

**Comment by BethedenMinistries** [comment]
The way the old system worked is that as you entered more glosses, it would intelligently autofill glosses according to confirmed glosses. So the you either have a field that's filled based on past confirmations, or based on Google translate. Each has a different color coding.  So the prefilling is the only thing that I see as a need to speed up the process. Autocompleting is probably going to cause more frustration and errors than anything else.  Typos should be avoided by spellcheck, rather than autocomplete. I still vote for option 1.

**Comment by arrocke** [comment]
Ok, I'm starting to get a better picture. A few more questions:

How does the old app choose to prefill a previously confirmed gloss rather than a google translate gloss? If the gloss has been confirmed in another verse, then it shows that instead of google translate?

Can you say more about how you think spellcheck could work? There's nothing in the browser that would let us spellcheck another language.

**Comment by BethedenMinistries** [comment]
Sheldon would have to speak to the first question.
I guess I imagined spell check working like it does everywhere else: it gets underlined in squiggly red, but only in the editable field. If a user visits the site and sees the public view of the site, no red underlines will show.

**Comment by BethedenMinistries** [comment]
Here's a video showing another facet of the problem I've experienced; https://youtu.be/z1BLoQonHN0

**Comment by arrocke** [comment]
[Design](https://www.figma.com/file/GYKTJWl1otgwpmA9ZLLthE/Gloss-Translation-App?type=design&node-id=1218-701&mode=design&t=4tqE0ADsS4nGJ9XJ-0) for this is complete. The work for this issue should address #182 as well. This is ready to be worked on.

## acceptance criteria
The autocomplete needs to work a little differently than it does now:
* As the user types, suggestions are shown from previous glosses filtered by what has been typed
* No suggestion is highlighted until the user uses the arrow keys to navigate the choices
* Tab/Enter - if a choice is highlighted, saves that gloss. otherwise, saves typed gloss. moves to next word

<img width="606" alt="Screen Shot 2023-09-27 at 9 41 56 PM" src="https://github.com/arrocke/gloss-translation/assets/11968925/1022a110-5434-4e2b-85c9-77dafb863ef1">
