### ISSUE TITLE
Lag when navigating to new verse

### ISSUE THREAD

**Issue by BethedenMinistries** [arrocke/gloss-translation#186]
When going to a new verse there's a significant lag (The lag isn't very significant when going back to a verse that has already loaded). It doesn't really make sense for loading one verse to take that long. Sheldon's site is super snappy in comparison, and I think that would be a nice standard to shoot for.  
Chrome browser.

**Comment by arrocke** [comment]
The big difference here is that we are loading data verse by verse, while the current app loads data a whole book at a time. So there is a similar amount of lag when you switch books in the current app. We can definitely improve this on the new version.

One tradeoff to consider is that if we load all of the data for the book or chapter, if it changes on the server because of another user, our data might be stale. That may not be a problem if it's unlikely users are looking at the same verses at the same time, but it is a tradeoff we need to consider.

@Pertempto I have a couple ideas for how to improve this. Let me know what you think.
1. Prefetch in advance. We can prime the client side cache with the next set of data before it is needed.
2. Load bigger chunks. This could be the entire book, a chapter, or a certain number of verses. It would reduce the number of requests needed navigating between verses.

**Comment by Pertempto** [comment]
I'd vote for initial tests with prefetch experiments. If that doesn't get us what we need, then load bigger chunks.

It seems like while a translator is working on the glosses for a verse, there is plenty of time to prefetch the next verse. Maybe even the next 10 verses.

**Comment by arrocke** [comment]
Yeah, I think that is the right approach. One thing we could do as well is write an API request that lets us fetch data for a verse range and use that to seed the cache. The advantage here is that with one request the cache would have data for multiple verses rather than needing multiple requests.

Let's start with ensuring that the next 3 verses are in the cache at all times, and go from there. If we need to prefetch more than that, we can try to load data in bulk.

**Comment by Pertempto** [comment]
Yeah the API improvement sounds like a great idea. Should save significant network loading time.

**Comment by arrocke** [comment]
Prefetching the next three verses worked will in my local testing. PR is open with the change.
