### ISSUE TITLE
Automatic advance to next verse

### ISSUE THREAD

**Issue by BethedenMinistries** [arrocke/gloss-translation#189]
When I save the last gloss in a verse it doesn't automatically take me to the next verse. 
So, if a user has already approved/saved all the glosses in a verse, and they hit Enter/Tab on the last word in the verse, it advances automatically to the next verse.
That's definitely an important feature to have before people start using it, since everyone is used to Sheldon's app doing that.

**Comment by arrocke** [comment]
Totally agree on making that navigation easy. However, It's generally considered bad practice to hijack the tab sequence like that. That's the universal standard for navigating through interactive elements with just a keyboard.

What I would propose we do instead is add a button to the end of the verse line so that when you tab off of the last word you can just hit Enter on that button to navigate to the next verse. This would not disrupt the tab sequence allowing you to tab past the button to interactive elements further down the page.

**Comment by BethedenMinistries** [comment]
Sounds good to me.

**Comment by arrocke** [comment]
[Design](https://www.figma.com/file/GYKTJWl1otgwpmA9ZLLthE/Gloss-Translation-App?type=design&node-id=1218-701&mode=design&t=4tqE0ADsS4nGJ9XJ-0) for this is done. This is ready to be worked on.

## acceptance criteria
* At the end of the translation line add a link to navigate to the next verse
* The text should be vertically aligned with the text of the gloss line

<img width="606" alt="Screen Shot 2023-09-27 at 10 03 28 PM" src="https://github.com/arrocke/gloss-translation/assets/11968925/6ff7a467-8c73-4119-84d6-394222773983">
