### ISSUE TITLE
Gloss alignment 

### ISSUE THREAD

**Issue by BethedenMinistries** [arrocke/gloss-translation#201]
I hate to be nitpicky, but it would be nice to have the glosses align right underneath the Hebrew when you're in editing mode. The arrow menu dropdowns offset the glosses significantly, and so you're eyes have to keep looking back at an angle to see what you're glossing. My ideal would be to get rid of those arrows or find a way to align them better.

**Comment by arrocke** [comment]
[Design](https://www.figma.com/file/GYKTJWl1otgwpmA9ZLLthE/Gloss-Translation-App?type=design&node-id=1218-701&mode=design&t=4tqE0ADsS4nGJ9XJ-0) for this is complete. This is ready to be worked on.

## acceptance criteria
* The edge of the original language, reference gloss and translated gloss will all be aligned.
* For Hebrew they will be aligned on the right edge, and for Greek on the left edge
* This means the edge of the dropdown menu will stick out a bit so that the edge of the text is aligned

<img width="606" alt="Screen Shot 2023-09-27 at 9 41 56 PM" src="https://github.com/arrocke/gloss-translation/assets/11968925/1022a110-5434-4e2b-85c9-77dafb863ef1">
