### ISSUE TITLE
Ability to delete suggested gloss

### ISSUE THREAD

**Issue by BethedenMinistries** [arrocke/gloss-translation#202]
If someone glosses a word and makes a mistake or changes their mind later, it would be nice to be able to delete that suggested gloss from showing up on the dropdown menu of options.

**Comment by arrocke** [comment]
@BethedenMinistries Are you wanting to delete the gloss for a specific word in a verse, or all uses of the specific gloss in the translated language regardless of what verse it is in?

**Comment by BethedenMinistries** [comment]
The point is to avoid the drop-down menu of suggested glosses from getting full of typos that were accidentally approved. So let's say I typed in Yeveh for God's name and approved it. Then I go back and fix it, but every time I hit the drop-down menu for God's name in the future, it has Yeveh as one of the suggested glosses.

**Comment by arrocke** [comment]
Ah, makes sense. We build that list from all of the glosses where that word appears in the Bible. It's not a separate list. So in my mind, rather than deleting the suggestion, we want to allow the user to specify a correction for that gloss and update it for every word that has the bad gloss. Then all of the words will be correct, and it will no longer be suggested.
