### ISSUE TITLE
Add and reorder translation preferences

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#208]
## acceptance criteria
* user needs to be able to add/remove reference translations
* user needs to be able to reorder translations according to their preference

**Comment by arrocke** [comment]
Here is a [figma](https://www.figma.com/file/GYKTJWl1otgwpmA9ZLLthE/Gloss-Translation-App?type=design&node-id=1272-651&mode=design&t=XEKe1lQk4w96Tjpk-0) design



![Image](https://github.com/arrocke/gloss-translation/assets/11968925/212268b8-83b9-4d1d-8e39-dc9b71f65b3b)

**Comment by Pertempto** [comment]
I like it!

**Comment by Pertempto** [comment]
Are we wanting to be able to re-order through two methods?
- drag and drop
- arrow buttons

If so, do we want to support drag and drop on mobile?

From the little research I did, it appears that drag and drop API support can be inconsistent across browsers. That might be outdated information, since [`caniuse`](https://caniuse.com/?search=drag%20and%20drop) says that 94% of internet users have access

**Comment by Pertempto** [comment]
# To Do
- [x] Basic structure
- [x] Implement re-order functionality
    - [x] With buttons
- [x] Implement delete functionality
- [x] Implement add functionality
- [x] Translation terms
- [x] Empty state

**Comment by arrocke** [comment]
I'd be fine if we wanted to implement just the arrow keys for now. Drag and drop is just a nice to have, but you need the arrow keys for accessibility. When I've worked with drag and drop before we had refactor to switch from the Drag and Drop browser API to pointer events because mobile support was so bad.

**Comment by Pertempto** [comment]
Ok, I'll just stick with the arrow buttons for now, since I don't think that the ROI would be high enough for trying to support drag and drop. We can add it later if we decide it becomes a higher priority.
