### ISSUE TITLE
Rework Language Code Input

### ISSUE THREAD

**Issue by Pertempto** [arrocke/gloss-translation#222]
The language code input has too many options to show at one time. Instead of using a `ComboboxInput`, let's use a simple input with validation that checks that a given language code is in the official list.

Original background: https://github.com/arrocke/gloss-translation/pull/217#discussion_r1349980119

**Comment by arrocke** [comment]
@Pertempto What do you think about just adding a validation message to confirm that the language code is valid? Since the user already has to look up the code in another system to figure out what the correct one is, I don't think there is much utility in trying to show a list that long or trying to filter.

**Comment by Pertempto** [comment]
That's a valid point. I'll rework the title/description
