### ISSUE TITLE
Gloss Suggestions Not Complete

### ISSUE THREAD

**Issue by Pertempto** [arrocke/gloss-translation#226]
**Describe the bug**
The autocomplete suggestion list isn't filled in with glosses that were just approved. I wonder if there is an issue in our caching behavior

**To Reproduce**
1. Go to verse ID `40002001` (Matthew 2:1) in the translate view, with the translator permission
2. Enter and approve two different glosses for "ἐν" (words `4000200105` and `4000200109`)
3. Click the next verse button to navigate to `40002002` (Matthew 2:2)
4. Click on the gloss input for "ἐν" in this verse (word ID `4000200214`)

**Expected behavior**
This word has the same form ID (`G1722-1`) as the previous two glosses, so I'd expect those two gloss options to show up in the autocomplete.

**Environment (please complete the following information):**

- Device: Laptop
- OS: Windows 11
- Browser: Vivaldi (chromium based)
- Version: `v0.3.3`

**Additional context**
Found this bug while testing https://github.com/arrocke/gloss-translation/pull/218

**Comment by Pertempto** [comment]
@arrocke I think I've seen this bug a couple times, I tried to find a hard set of steps to trigger it before I forgot about it.

**Comment by arrocke** [comment]
Because we prefetch all of the data for the next few verses, that data can be out of date when the user gets to that verse. If you refresh the page, you'd see that those suggestions are there now.

A couple ideas to solve this:
* Separate out the current glosses from the suggestion data. We can prefetch everything except the suggestions since those can change from verse to verse. The suggestions are then the only thing we have to prefetch on every verse navigation
* When glosses are approved, programmatically update the suggestions for all verses in the cache.
* Cache suggestions for different lemma forms on the client side according to lemma and form Id. We can update this cache when glosses are approved, and only load the suggestions for the lemma forms we don't have yet when a verse loads.
