### ISSUE TITLE
Handing Ketiv & Qere in Hebrew

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#266]
Ketiv - what is written
Qere - what is said

I'm assuming our readers Bible will privilege the Qere, so we should for sure gloss that. The question is whether we want to gloss the Ketiv as well, or will we just show it as a footnote in the readers Bible. I know that the Ketiv has the Qere vowels usually, so that might be a point against glossing it.

**Comment by arrocke** [comment]
@BethedenMinistries Andrew, what are your thoughts on this?

**Comment by BethedenMinistries** [comment]
![Screenshot (9)](https://github.com/arrocke/gloss-translation/assets/98789828/fde48e65-f78b-4272-bd1b-29e5bef49937)
![Screenshot (10)](https://github.com/arrocke/gloss-translation/assets/98789828/b744cf89-53df-480b-97f2-5cbaf5308393)
Just for illustration, here's how the BHS handles K-Q readings and how Sheldon's app handles them.  So you can see that the BHS adds vowels to the Qere in a footnote, and keeps the vowels on the Kethiv in the main text, and Sheldon's strips the vowels off of what appears in the main text, and only includes them on the Qere (what should be read).

**Comment by BethedenMinistries** [comment]
Personally I like the simplicity of how Sheldon's app handles it. The gloss volunteer wouldn't have to gloss what is written if it doesn't make sense or is too difficult, but only what is read. If the Kethiv (what is written) is glossable, then I think it would be helpful to gloss it so that people can weigh both for themselves. So in the example of Esther above, it's only a difference of prepositions, so that's easy to represent in the glosses.

**Comment by arrocke** [comment]
Ok, that's helpful. We are currently handling it the way Sheldon's app does because we have the same underlying dataset, and I think that is a fine way to approach it. I'll go ahead and close this since this already complete
