### ISSUE TITLE
second guessing mongodb

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#35]
I had a conversation with a coworker about NoSQL vs SQL today that has me second guessing our decision to go with mongo. If we were to use a SQL database, it would probably look something similar to this:

```mermaid
erDiagram
  BOOK ||--|{ CHAPTER : contains
  CHAPTER ||--|{ VERSE : contains
  VERSE ||--|{ WORD : contains
  WORD }|--|| FORM: has
  FORM }|--|| LEMMA : has
  LANGUAGE ||--|{ GLOSS : contains
  GLOSS ||--|| WORD : references

  BOOK {
    number id PK
    string name
  }

  CHAPTER {
    number id PK
    number bookId FK
    number number 
  }

  VERSE {
    number id PK
    number chapterId FK
    number number
  }

  WORD {
    number id PK
    number verseId FK
    ID lemmaId FK
    string text
  }

  FORM {
    ID id PK
    ID lemmaId FK
    string text
    string grammarCode
  }

  LEMMA {
    ID id PK
    string text
    number strongs
  }

  GLOSS {
    ID id PK
    ID languageId FK
    ID wordId FK
    string gloss
  }

  LANGUAGE {
    ID id PK
    string name
  }
```

If that is the case, then to query all glosses for a lemma would be a query something like this. My SQL is a bit rusty so this might not be exactly right.
```sql
SELECT Book.name, Chapter.number, Verse.number, Word.id, Gloss.text, Form.text
FROM Form
JOIN Word On Word.formId=Form.id
JOIN Gloss On Gloss.wordId=Word.id
JOIN Verse On Word.verseId=Verse.id
JOIN Chapter On Verse.chapterId=Chapter.id
JOIN Book On Chapter.bookId=Book.id
WHERE Form.lemmaId=<lemma id> AND Gloss.languageId=<language id>
```

Now that is a lot of joins, but keep in mind that there are 443,000 words in the ancient languages. And besides Yaweh and God, all other words are used less than 3000 times. So that means the lookup of words is going to pull out in most cases <3000 words from 443,000 and then join that against the verse/chapter/book tables which will all be small, and against the gloss table which if we index by language id should be fast as well regardless of how many languages we end up supporting. I think if we were to look at fetching a verse with its glosses and grammar information, it would be similar.

Now, for mongodb to give us the benefit of speed we have to store the gloss information twice, once with the verse and once with the lemma and form. You can't rely on joins for speed in mongo.

Now the key question that I have is whether it is worth the added complexity to denormalize our data with mongo in order to get some perceived speed boost in queries? The reason I went through that exercise is because I'm really wondering whether our data is going to be large enough even with 40+ languages for a sql server to struggle to deliver this data in a timely manner. I'm not super familiar with SQL, so maybe this is rather obvious. But if sql can handle our data, then we should not saddle ourselves with the added complexity and constraints of a nosql database.

**Comment by Pertempto** [comment]
> Now the key question that I have is whether it is worth the added complexity to denormalize our data with mongo in order to get some perceived speed boost in queries? 

I've never had to push SQL to its limits in terms of performance so I'm not really sure I can answer. I think either way we go, the queries are going to be plenty fast enough.  

> But if sql can handle our data, then we should not saddle ourselves with the added complexity and constraints of a nosql database.

This kind of threw me off, because I thought the benefits of a nosql DB were LESS complexity and constraints. I must've misunderstood. My experience with working with a SQL DB at work have not been great, but that might be because the DB wasn't designed very well. If we start from the onset with a good ORM like [TypeORM](https://typeorm.io), it should (ideally) handle a lot of the integration headaches for us.   
For example, TypeORM has [automatic migration generation](https://typeorm.io/migrations#generating-migrations). We haven't been able to use those yet, because our codebase still contains a mix of raw SQL and TypeORM queries. Instead we use the [db-migrate](https://db-migrate.readthedocs.io/en/latest/) system, which means every time we want to add a new column to a table, we have to write some raw SQL for the up and down migrations. This is a BIG pain, error-prone, and not great for developers.


I feel that developer experience should be a bigger priority than performance in our decision-making process for DB. The performance differences really shouldn't be that significant for the volume of data we'll be working with, like you said. The big thing that appealed to me about mongoDB was that it appeared to be much easier to integrate with TypeScript. Maybe my bad experiences with using raw SQL in TypeScript (not the ideal at all) have biased me away from using a SQL DB.

**Comment by arrocke** [comment]
> This kind of threw me off, because I thought the benefits of a nosql DB were LESS complexity and constraints.

It's all about trade-offs. A NoSQL database can be easier to use because it requires no schema, its document model maps onto the javascript object really nicely, and for mongo, its queries can be expressed in JSON. So yes, for many projects it can be easier to use. However, because joins are expensive, you have to be intentional about designing the db structure so that queried data is always together, which makes insertion and updating of data more complex. You reduce the complexity and increase the speed of queries at the cost of increasing complexity of data mutations.

I pitched mongodb to you on the basis that our particular data would benefit from the mongodb query advantages, which would make the complexity cost of keeping it updated worth it. We really want to preserve the speed of stuff like BibleWorks. It's that assumption that I'm second guessing. Because the number of records we are talking about is relatively small, the gains of using a query optimized approach are likely minimal. At my job we are using MongoDB like a sql database which is causing us problems because we aren't getting the benefits and paying the cost of expensive joins. That's the situation I want to avoid.

> I feel that developer experience should be a bigger priority than performance in our decision-making process for DB. The performance differences really shouldn't be that significant for the volume of data we'll be working with, like you said.

This is a great point, and is why I'm bringing this up again. I'm concerned that the work necessary to update multiple documents to preserve the speed of queries is going to be unnecessary work and make our data harder for new people to understand. But, to solve the ORM problem, I think we should look at prisma. I think that will have a similar developer experience to mongo.

Prisma lets your express your db model in code, and write migrations to update it automatically. It also generates a typescript db client that matches the model. That client has very similar features to the mongodb client, but its already got the types for our specific database.

Here would be my suggestion: Let me put up a branch with a prisma connected to a local postgres database. We can define tables for books, chapters, and verses, write a text API route, and look at how migrations work to add a new table for languages. Then we can evaluate where to go from there

**Comment by Pertempto** [comment]
Alright, that sounds good.

This article was useful to me: https://www.prisma.io/docs/concepts/more/comparisons/prisma-and-typeorm
