### ISSUE TITLE
Brainstorm ideas for translating lexicons with vscode extensions

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#385]
We will use this ticket to keep track of ideas and questions related to using vscode extensions to translate lexicons.

## Major Questions
- [ ] What will the editor look like to produce a translation for a single lexicon entry?
- [ ] What reference material do want to show in parallel?
  * list of verses that use the word in a variety of translations
  * reference entry in a variety of languages
  * preview of entry as it is filled out
  * selector of words in the lexicon to navigate to
- [ ] How can we use git and vscode diffing tools to track, review, and accept changes?
- [ ] How will we store reference data locally?
- [ ] What AI tools do we want to incorporate to speed up translation?
- [ ] What information can we synthesize from entries to speed up translation? This would be ideas along the lines of gloss suggestions from previous approved words.

**Comment by Pertempto** [comment]
So far I've mostly experimented with `vscode.commands.registerCommand`, which is super nice to work with!

Next, I will experiment with the custom views feature.

@arrocke do you have a github repo with that demo you posted in slack?

**Comment by arrocke** [comment]
I just pushed a repo with what I had on my computer: https://github.com/arrocke/vscode-extension-testing

**Comment by Pertempto** [comment]
ok, thanks! that should help me get started with learning custom views

**Comment by Pertempto** [comment]
Stuff I learned while working with custom editors...

- How to keep contents of web view in sync with the document - [docs](https://code.visualstudio.com/api/extension-guides/custom-editors#synchronizing-changes-with-the-textdocument)
- How to load web view HTML from other file
- The `vscode` object returned from `acquireVsCodeApi` inside the webview is VERY limited.
- All data processing should occur in the extension code. The webview can send and receive data through message events.
  - This can be a little tedious to setup.

**Comment by Pertempto** [comment]
All the web view examples I saw showed loading the HTML for the web view for a customer editor from a javascript string. I found this very inconvenient. Here is a way to load the HTML from a separate file:

```js
        const fs = workspace.fs;
        const pathToHtml = Uri.file(
            path.join(
                this.context.extensionPath,
                "editor-content",
                "sequence",
                "main.html"
            )
        );

        webviewPanel.webview.options = { enableScripts: true };

        fs.readFile(pathToHtml).then((data) => {
            webviewPanel.webview.html = data.toString();
        });
```

**Comment by craigalodon** [comment]
I wish I had more of the technical skills to contribute to some of this discussion, but I did want to comment a bit on the broader concept, as regards translating a lexicon entry. These are just my thoughts. I have pretty good experience with the Biblical languages, especially with Classical Greek, but I'm not a professional translator or otherwise employed to work with the languages, so my opinions don't carry a ton of weight. 

Nonetheless, as to what sort of reference material might be useful:

1. I don't know that providing a list of references to verses that use the word makes a lot of sense. Almost any decent lexicon already does that in the entry itself. So, I feel like that would be reduplicating a lot of information. Maybe there is something I'm missing, but if you are looking at your average lexicon, say the Brown-Driver-Briggs, the entry is significantly made up of references to Biblical citations. I can only think of two exceptions to this:

- Dictionaries that are focused primarily on non-Biblical material, which could be true for some Greek lexicons. In those cases, it will still be full of references, but not to Biblical ones.

- While simply providing reference lists adds very little IMO, providing some sort of hot linking to actually preview those references could be valuable. In this case, the desired functionality would be akin to that in reftagger or major Bible software apps, where you can preview or jump to the referenced verse to see what it looks like in translation. I'm not a translator, but that might be helpful.

2. I do think the ability to quickly navigate along a tree of related entries might be useful. I can imagine that translators would find it convenient and desirable to simply follow along a tree of related words, and/or would want to check for consistency across them. So, I think that function could be helpful, and worth developing out. Likewise, on the back end, it might be useful to identify these trees of cross-linked word-families, so that translation teams could identify low-hanging fruit, that is, families of linked entries that could be completed together.

3. On the AI tools, again, this is a bit out of my wheelhouse. I wonder if AI could be useful for handling things that presumably are somewhat generic across languages, such as citation formatting/styling. I'm not sure, but I could imagine a fair amount of busy work on the part of the translators to convert from the source language reference style to the target. I'm not really sure how big of a problem this is or not, but it strikes me as precisely a part of translation that is highly formalistic and doesn't really require a ton of human judgment or thought to do.

**Comment by arrocke** [comment]
Thanks for the feedback, this is super helpful. A couple thoughts this has spawned for me:

1. This is good advice. The lexicon we are translating is the semantic dictionary from UBS. You can see an example entry here: https://marble.bible/dictionary?s=000003000000000&db=Hebrew. Each entry can expand to show the lexical entries. We may not need a separate reference tool for verse references if we can open the reference from the text being translated directly.
2. This also should work well with the semantic dictionary because words are grouped into lexical and contextual domains for us, which we could expose in a tree view of sorts in the editor. This view gives you the option to see the lexical domain tree: https://marble.bible/graph
3. In my mind there are two things we should try to use computers for:
    * Automate the translation of things like common terms (noun, qal, imperfect, etc), verse references, and anything else. This is what you suggest here.
    * Offer suggestions or offer predictions as you type translations of things like descriptions, glosses, etc.

**Comment by arrocke** [comment]
I'm going to close this issue in favor of issues in globalbibletools/lexicon-translation
