### ISSUE TITLE
right to left layout

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#85]
## acceptance criteria
* Reverse the layout for languages that are right to left

**Comment by Pertempto** [comment]
Is there an easy way to determine when a language is right to left?

**Comment by arrocke** [comment]
i18next has the [dir](https://www.i18next.com/overview/api#dir) property that is available on the `i18next` property in `useTranslation`

**Comment by Pertempto** [comment]
To Do:
- [ ] fix dropdown menus
- [ ] fix icon ordering when beside text
- [ ] saving text
- [ ] language selector
- [ ] manage language page
- [ ] ...

**Comment by Pertempto** [comment]
I found the [`dir` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir), which makes a lot of this happen automatically.  
Using the [`tailwindcss-rtl` library](https://github.com/20lives/tailwindcss-rtl), we can now use things like `ms-0` instead of `ml-0`, and `text-start` instead of `text-left`.

**Comment by arrocke** [comment]
Do you think that is a better solution that what tailwind has [built in](https://tailwindcss.com/docs/hover-focus-and-other-states#rtl-support)? That library doesn't have a lot of use and hasn't had a release since Feb 2022

**Comment by Pertempto** [comment]
That is a good point. I didn't notice that tailwind has built in rtl modifiers. I do think it is much easier to read and write `ms-3` instead of `ltr:ml-3 rtl:mr-3`
